server:
  port: 9007
spring:
  application:
    name: tensquare-search #服务器名字
#  es与java交互的默认端口号是9300，与http交互的端口号是9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enable: true
